### ISSUE TITLE
表紙画像のファイル選択が指定がないためなんでも選べるようになっている

### ISSUE THREAD

**Issue by PtMK2** [Mitsutan/2023Dev3Early#13]
エクセルファイルを選択したら、ファイルは選択できたが、投稿しても何も起こらなかった。

**Comment by ZumiZumiZumi** [comment]
ファイル選択を表示している<input type="file" name="topimg">に
 accept = "image/*"　を追加することで解決した
あくまでユーザーヒントなので初期選択が画像系の拡張子のものしか表示されないだけで選択しようとしたらできてしまう　受け付けないようにもできると思うけどどうしますか。

**Comment by ZumiZumiZumi** [comment]
ファイル選択を表示しているに
accept = "image/*"　を追加することで解決した
あくまでユーザーヒントなので初期選択が画像系の拡張子のものしか表示されないだけで選択しようとしたらできてしまう　受け付けないようにもできると思うけどどうしますか。

**Comment by Mitsutan** [comment]
時間があったら対応するってことで、いったんクローズ
