### ISSUE TITLE
新規記事の内容に画像ファイル以外のファイルを張ったらエラーが出まくった。

### ISSUE THREAD

**Issue by PtMK2** [Mitsutan/2023Dev3Early#14]
![バグ](https://github.com/Mitsutan/2023Dev3Early/assets/116693608/8a31dc0e-37be-464c-85e8-185b9427fa4e)
![バグ1-2](https://github.com/Mitsutan/2023Dev3Early/assets/116693608/62cd5ad1-d189-4e42-89ad-453a02639d9b)
](url)

**Comment by Mitsutan** [comment]
画像ファイル以外は受け付けないように修正しました
