### ISSUE TITLE
検索画面でスクロールすると、検索ボタンがヘッダーの上に被る

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#17]
![スクリーンショット (522)](https://github.com/Mitsutan/2023Dev3Early/assets/83488293/96647850-0f5a-403f-9c51-199fd56d86b3)

**Comment by Mitsutan** [comment]
検索フィールドをアクティブにしたらそれも被るらしい

**Comment by ZumiZumiZumi** [comment]
修正完了
