### ISSUE TITLE
画面設計書関連　全体

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#2]
### やること
- [x] サイトマップ
- [x] 画面モックアップ（figma）
- [x] 画面一覧
- [x] 画面遷移図
- [x] 画面レイアウト

02_画面設計書の中にサイトマップのppが入っています。
追加したほうがいいページの提案や作業などをここにどうぞ

**Comment by Mitsutan** [comment]
ユーザーページって必要ですよね？

**Comment by Mitsutan** [comment]
現在「マイページ」から「ログイン」となっていますが、これは未ログインだったらログイン画面に飛ばすという認識で大丈夫ですか。

**Comment by PtMK2** [comment]
> 現在「マイページ」から「ログイン」となっていますが、これは未ログインだったらログイン画面に飛ばすという認識で大丈夫ですか。

自分もその認識です。

**Comment by Mitsutan** [comment]
figmaでは記事にフォローボタンがあるみたいですけど、これどんなふうにしますか
フォローしたらどうなるのかがよく分からない

**Comment by Mitsutan** [comment]
レビューNo.6について、とりあえず案２で進めることになりましたがよろしいですか
