### ISSUE TITLE
画面設計書　figma

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#3]
#2 画面設計書　全体

担当者
- @Mitsutan 
- @ZumiZumiZumi 

何かあればここへ連絡

**Comment by PtMK2** [comment]
筋トレ紹介の種目です
胸
背中
二頭
三頭
肩
腹筋
四頭筋
ハムストリングス
ふくらはぎ
大殿筋（お尻）

**Comment by PtMK2** [comment]
https://www.goldsgym.jp/
デザインの参考資料です
