### ISSUE TITLE
画面設計書　設計書

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#4]
#2 画面設計書　全体

担当者
- @Ryuking2525 
- @ASO2201114 
- @2201116 
- @PtMK2 

何かあればここへ連絡

**Comment by ZumiZumiZumi** [comment]
画面設計書の部品の入力についてお願いしたいのですが、ヘッダーは全画面に入ってくるので書き方を先に統一したいです。

**Comment by Ryuking2525** [comment]
了解です。

**Comment by PtMK2** [comment]
わかりました。

**Comment by ASO2201114** [comment]
トップページの記事画面に遷移するボタンは記事の見出しor画像どちらですか？

**Comment by Mitsutan** [comment]
カード全体に判定あるかなって思ってたけど、どちらでもいいです

**Comment by ASO2201114** [comment]
カード全体だとフォローするボタンを押すときに不便だと思います

**Comment by Mitsutan** [comment]
画像とタイトルでby zumi

**Comment by Mitsutan** [comment]
> カード全体だとフォローするボタンを押すときに不便だと思います

前回の開発でカード全体に判定をつけた際には、とくに操作上の不都合はなかったのでその点は大丈夫だと考えます。
逆にピンポイントで見出しをクリックしないと記事に遷移できないイラつきのほうが大きかった...

まあこの辺は好みによるのでみんながどうしたいか聞きたいな

**Comment by Ryuking2525** [comment]
![IMG_4965](https://github.com/Mitsutan/2023Dev3Early/assets/116329044/5a661c02-dd13-4f86-89d3-12a7cccb0174)

**Comment by Ryuking2525** [comment]
![IMG_4945](https://github.com/Mitsutan/2023Dev3Early/assets/116329044/b254e9e7-6f38-4ee6-8ce4-57cf9d3a53d1)

**Comment by Mitsutan** [comment]
設計書ですが、当初の作成者が不明なページは「グループ５」と記入しておきます。
「自分が書いてたのに...」って方は名前を書き換えてください。
