### ISSUE TITLE
ヘッダーの「いいね」につけるアイコン

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#7]
[font awesome](https://fontawesome.com/search?o=r&m=free)で上腕二頭筋💪のアイコンが見つからなかったのですが、なにか代用案ありますか？

**Comment by ZumiZumiZumi** [comment]
アイコンの画像の文字を消して使いませんか

**Comment by Mitsutan** [comment]
もういいんじゃね
