### ISSUE TITLE
記事カードの高さが不揃いになる

### ISSUE THREAD

**Issue by Mitsutan** [Mitsutan/2023Dev3Early#9]
![スクリーンショット (514)](https://github.com/Mitsutan/2023Dev3Early/assets/83488293/e4f195e9-89c5-4e05-b3be-6e262de94c7f)
送付画像のように、記事にタグがあるときと無いときでカードの高さが一致しません。
どうしよう

**Comment by ZumiZumiZumi** [comment]
タグの有無に関わらずにデフォルトで
タグ：
を表示して1行分確保しとくとか？　タグ多すぎてもずれる？

**Comment by Mitsutan** [comment]
タグ多すぎてもズレます

**Comment by Mitsutan** [comment]
カード本体の子要素（？）にh-100を指定すると外枠の高さはそろうみたい
中はいまだずれるけど

![スクリーンショット (517)](https://github.com/Mitsutan/2023Dev3Early/assets/83488293/6a487350-bd97-4967-a665-ba17792cfb35)
